In [1]:
import numpy as np

In [67]:
def test_array(a, b):
    if not np.allclose(a, b.flatten()):
        first = int(np.where((a == b) == False)[0][0])
        msg = f"\n 1er elemento con error: {first}.\n valor correcto {a[first]}, \n valor calculado {b[first]}\n"
    #    np.testing.assert_equal(a, b,err_msg=msg)
        return np.testing.assert_allclose(a, b,err_msg=msg)
    

In [40]:
a = np.array([[1,2j],[2,3]])#, dtype=complex)
b = np.array([4,3,2j,1])

print(a)
for i,c in enumerate(a.flatten()):
    print(i, c, c.real, c.imag)
    
print()
print(b)
for i,c in enumerate(b.flatten()):
    print(i, c, c.real, c.imag)

print()
if a.dtype == complex:
    l_c = np.array([[c.real, c.imag] for c in a.flatten()]).flatten()
print(l_c)

if b.dtype == complex:
    l_c = np.array([[c.real, c.imag] for c in b.flatten()]).flatten()
print(l_c)


[[1.+0.j 0.+2.j]
 [2.+0.j 3.+0.j]]
0 (1+0j) 1.0 0.0
1 2j 0.0 2.0
2 (2+0j) 2.0 0.0
3 (3+0j) 3.0 0.0

[4.+0.j 3.+0.j 0.+2.j 1.+0.j]
0 (4+0j) 4.0 0.0
1 (3+0j) 3.0 0.0
2 2j 0.0 2.0
3 (1+0j) 1.0 0.0

[1. 0. 0. 2. 2. 0. 3. 0.]
[4. 0. 3. 0. 0. 2. 1. 0.]


In [38]:
print(a)
for i,c in enumerate(a.flatten()):
    print(i, c, c.real, c.imag)
    
print()
print(b)
for i,c in enumerate(b.flatten()):
    print(i, c, c.real, c.imag)

[[1.+0.j 0.+2.j]
 [2.+0.j 3.+0.j]]
0 (1+0j) 1.0 0.0
1 2j 0.0 2.0
2 (2+0j) 2.0 0.0
3 (3+0j) 3.0 0.0

[4.+0.j 3.+0.j 0.+2.j 1.+0.j]
0 (4+0j) 4.0 0.0
1 (3+0j) 3.0 0.0
2 2j 0.0 2.0
3 (1+0j) 1.0 0.0


In [43]:
lista_lista = [[1,2],[3,4]]
len(np.array(lista_lista).flatten())

4

In [51]:
s = np.array(list({3, 5, 6, 2, 9,8,3}))
print(s, type(s), len(s))

[2 3 5 6 8 9] <class 'numpy.ndarray'> 6
